(()=>{"use strict";
const DB="clairity",VER=1,EVIDENCE="evidence",SETTINGS="settings";
const state={route:"today",module:null,db:null,settings:{enabledModules:["sleep"]}};
const registry=new Map();
registry.set("sleep",Object.freeze({id:"sleep",name:"Sleep",icon:"☾",description:"Duration and quality",version:1,summarize:summarizeSleep}));
const el={main:document.querySelector("#main-content"),title:document.querySelector("#page-title"),subtitle:document.querySelector("#page-subtitle"),status:document.querySelector("#save-status"),statusText:document.querySelector("#save-status b"),nav:[...document.querySelectorAll(".nav-item")]};
document.addEventListener("DOMContentLoaded",init);
async function init(){bindNav();try{state.db=await openDb();state.settings=await loadSettings();setStatus("saved","Saved locally")}catch(e){console.error(e);setStatus("failed","Storage unavailable")}await render()}
function bindNav(){el.nav.forEach(b=>b.addEventListener("click",async()=>{state.route=b.dataset.route;state.module=null;await render()}))}
async function render(){el.nav.forEach(b=>b.classList.toggle("active",b.dataset.route===state.route));if(state.module)return renderModule();const meta={today:["Today",longDate(new Date())],history:["History","Recorded evidence, including retrospective entries"],insights:["Insights","Evidence first. Uncertainty made visible."],settings:["Settings","Modules and data on this device"]}[state.route];el.title.textContent=meta[0];el.subtitle.textContent=meta[1];if(state.route==="today")await renderToday();else if(state.route==="history")await renderHistory();else if(state.route==="insights")renderInsights();else renderSettings();el.main.focus({preventScroll:true})}
async function renderToday(){const records=state.db?await allEvidence():[];const today=dateKey(new Date());const cards=state.settings.enabledModules.map(id=>registry.get(id)).filter(Boolean).map(m=>{const r=records.find(x=>x.moduleId===m.id&&x.evidenceDate===today);return `<button class="module-card" data-module="${m.id}"><span class="module-row"><span class="icon">${m.icon}</span><span><strong>${m.name}</strong><span class="sub">${m.description}</span></span><span>›</span></span><span class="state ${r?"has":""}">${r?m.summarize(r.payload):"Nothing recorded"}</span></button>`}).join("");el.main.innerHTML=`<div class="stack"><section class="card intro"><p class="label">Today</p><h2>Record what matters when it happens.</h2><p class="copy">There is no check-in to finish. Each area works independently and every valid input is saved as you make it.</p></section><section class="stack"><div><p class="label">Evidence areas</p><h2>Available now</h2></div><div class="modules">${cards||`<div class="card empty"><h2>No active modules</h2><p class="copy">Enable one in Settings.</p></div>`}</div></section></div>`;el.main.querySelectorAll("[data-module]").forEach(b=>b.addEventListener("click",async()=>{state.module=b.dataset.module;await render()}))}
async function renderModule(){const m=registry.get(state.module),today=dateKey(new Date()),existing=state.db?await getEvidence(m.id,today):null;el.title.textContent=m.name;el.subtitle.textContent="Each valid change saves automatically";el.main.innerHTML=`<section class="card panel"><div class="panel-head"><button class="back" aria-label="Back">←</button><div><p class="label">Evidence module</p><h2>${m.name}</h2></div></div><div id="editor"></div></section>`;el.main.querySelector(".back").onclick=async()=>{state.module=null;await render()};renderSleepEditor(document.querySelector("#editor"),existing?.payload||{},today)}
function renderSleepEditor(box,p,defaultDate){let quality=Number.isInteger(p.quality)?p.quality:null;box.innerHTML=`<form class="form"><div class="field"><label for="sleep-date">Which day should this sleep belong to?</label><input id="sleep-date" name="evidenceDate" type="date" value="${p.evidenceDate||defaultDate}"><p class="help">Retrospective entries are valid. Clairity also preserves when you entered them.</p></div><div class="row"><div class="field"><label for="bed">Went to bed</label><input id="bed" name="bedTime" type="time" value="${p.bedTime||""}"></div><div class="field"><label for="wake">Woke up</label><input id="wake" name="wakeTime" type="time" value="${p.wakeTime||""}"></div></div><fieldset class="field"><legend>Sleep quality</legend><p class="help">Optional. Unselected remains unrecorded—not neutral.</p><div class="scores">${[1,2,3,4,5].map(n=>`<button type="button" data-score="${n}" aria-pressed="${quality===n}">${n}</button>`).join("")}</div></fieldset><div class="field"><label for="notes">Context or notes</label><textarea id="notes" name="notes" placeholder="Optional">${escapeHtml(p.notes||"")}</textarea></div><div class="notice">There is no Save or Finish button. Valid changes are saved automatically on this device.</div><button class="danger" type="button" data-clear>Clear this sleep record</button></form>`;const f=box.querySelector("form"),payload=()=>({evidenceDate:f.evidenceDate.value,bedTime:f.bedTime.value,wakeTime:f.wakeTime.value,quality,notes:f.notes.value.trim()}),persist=()=>saveEvidence("sleep",payload());[f.evidenceDate,f.bedTime,f.wakeTime].forEach(i=>i.addEventListener("change",persist));let timer;f.notes.addEventListener("input",()=>{clearTimeout(timer);setStatus("saving","Saving…");timer=setTimeout(persist,500)});box.querySelectorAll("[data-score]").forEach(b=>b.onclick=async()=>{const n=Number(b.dataset.score);quality=quality===n?null:n;box.querySelectorAll("[data-score]").forEach(x=>x.setAttribute("aria-pressed",String(Number(x.dataset.score)===quality)));await persist()});box.querySelector("[data-clear]").onclick=async()=>{if(confirm(`Clear the sleep evidence for ${formatDate(f.evidenceDate.value)}?`)){await del(EVIDENCE,`sleep:${f.evidenceDate.value}`);setStatus("saved","Saved locally");await renderModule()}}}
async function renderHistory(){const rows=(state.db?await allEvidence():[]).sort((a,b)=>b.evidenceDate.localeCompare(a.evidenceDate));el.main.innerHTML=rows.length?`<div class="history">${rows.map(r=>{const p=r.payload,d=duration(p.bedTime,p.wakeTime),vals=[p.bedTime&&`Bed ${p.bedTime}`,p.wakeTime&&`Wake ${p.wakeTime}`,Number.isInteger(p.quality)&&`Quality ${p.quality}/5`,d].filter(Boolean);return `<article class="card history-item"><div class="history-top"><div><strong>${formatDate(r.evidenceDate)}</strong><div class="meta">Sleep</div></div><div class="meta">Updated ${formatTime(r.updatedAt)}</div></div><div class="pills">${vals.map(v=>`<span class="pill">${v}</span>`).join("")||`<span class="pill">Evidence recorded</span>`}</div>${p.notes?`<p class="copy">${escapeHtml(p.notes)}</p>`:""}</article>`}).join("")}</div>`:`<section class="card empty"><h2>No evidence recorded yet</h2><p class="copy">History will appear after the first valid interaction is saved.</p></section>`}
function renderInsights(){el.main.innerHTML=`<section class="card empty"><p class="label">Phase 0 foundation</p><h2>Insights need evidence first</h2><p class="copy">This area is intentionally honest and empty. Clairity will not invent patterns from too little data.</p></section>`}
function renderSettings(){const enabled=state.settings.enabledModules.includes("sleep");el.main.innerHTML=`<div class="stack"><section class="card settings"><div class="panel-head"><div><p class="label">Modules</p><h2>Active evidence areas</h2></div></div><div class="setting"><div><strong>Sleep</strong><div class="sub">Disabling hides it from Today but preserves history.</div></div><input class="toggle" type="checkbox" data-toggle ${enabled?"checked":""}></div></section><section class="card settings"><div class="panel-head"><div><p class="label">Storage</p><h2>Local device data</h2></div></div><div class="setting"><div><strong>IndexedDB</strong><div class="sub">Not yet backed up or synchronised across devices.</div></div></div></section></div>`;el.main.querySelector("[data-toggle]").onchange=async e=>{state.settings.enabledModules=e.target.checked?["sleep"]:[];await saveSettings()}}
async function saveEvidence(moduleId,payload){if(!state.db)return setStatus("failed","Storage unavailable");const has=Object.entries(payload).some(([k,v])=>k!=="evidenceDate"&&v!==""&&v!==null);if(!has){await del(EVIDENCE,`${moduleId}:${payload.evidenceDate}`);return setStatus("saved","Saved locally")}setStatus("saving","Saving…");try{const old=await getEvidence(moduleId,payload.evidenceDate),now=new Date().toISOString();await put(EVIDENCE,{id:`${moduleId}:${payload.evidenceDate}`,moduleId,moduleVersion:1,evidenceDate:payload.evidenceDate,source:"manual",payload,createdAt:old?.createdAt||now,recordedAt:old?.recordedAt||now,updatedAt:now});setStatus("saved","Saved locally")}catch(e){console.error(e);setStatus("failed","Save failed")}}
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,VER);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(EVIDENCE)){const s=d.createObjectStore(EVIDENCE,{keyPath:"id"});s.createIndex("evidenceDate","evidenceDate");s.createIndex("moduleId","moduleId")}if(!d.objectStoreNames.contains(SETTINGS))d.createObjectStore(SETTINGS,{keyPath:"key"})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
function store(name,mode="readonly"){return state.db.transaction(name,mode).objectStore(name)}function req(q){return new Promise((res,rej)=>{q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}function get(name,key){return req(store(name).get(key))}function put(name,v){return req(store(name,"readwrite").put(v))}function del(name,key){return req(store(name,"readwrite").delete(key))}function all(name){return req(store(name).getAll())}function getEvidence(m,d){return get(EVIDENCE,`${m}:${d}`)}function allEvidence(){return all(EVIDENCE)}
async function loadSettings(){const x=await get(SETTINGS,"app");return x?.value||state.settings}async function saveSettings(){setStatus("saving","Saving…");await put(SETTINGS,{key:"app",value:state.settings,updatedAt:new Date().toISOString()});setStatus("saved","Saved locally")}
function summarizeSleep(p){const d=duration(p.bedTime,p.wakeTime);return d&&Number.isInteger(p.quality)?`${d} · quality ${p.quality}/5`:d||(Number.isInteger(p.quality)?`Quality ${p.quality}/5`:p.notes?"Context recorded":"Evidence recorded")}
function duration(b,w){if(!b||!w)return"";const [bh,bm]=b.split(":").map(Number),[wh,wm]=w.split(":").map(Number);let mins=wh*60+wm-(bh*60+bm);if(mins<=0)mins+=1440;return `${Math.floor(mins/60)}h${mins%60?` ${mins%60}m`:""}`}
function setStatus(s,t){el.status.dataset.state=s;el.statusText.textContent=t}function dateKey(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function longDate(d){return new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long"}).format(d)}function formatDate(k){const[y,m,d]=k.split("-").map(Number);return new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"numeric",month:"short",year:"numeric"}).format(new Date(y,m-1,d))}function formatTime(i){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(i))}function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
})();

